In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.3


In [9]:
my_list = [1,2,3,4]

print(my_list)

[1, 2, 3, 4]


In [12]:
my_list2 = my_list * 2

print(my_list2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [14]:
array = np.array([1,2,3,4])

print(array)

print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>



<p style="font-size:28px; font-weight:bold;">Multi Dimensional Array</p>


In [18]:
zeroD = np.array('A')

print(zeroD.ndim) #ndim = number of dimensions

0


In [17]:
oneD = np.array(['A'])

print(oneD.ndim)

1


In [21]:
twoD = np.array([['A'],
               ['B'],
               ['C']])

print(twoD.ndim)

2


In [32]:
threeD = np.array([[['A'], ['B']],
               [['C'], ['D']],
               [['E'], ['F']]])

print(threeD.ndim) #every single list should contain same number of elements as others, or there will be an error

3


In [31]:
print(threeD.shape) # here 3 layers, 2 rows in each layers, 1 column

(3, 2, 1)


In [30]:
print(threeD[0][0][0]) #This is chain indexing and not required for np array

A


In [29]:
print(threeD[0, 0, 0]) #np has this technique called multidimensional indexing

A


In [34]:
print(threeD[1,1,0])

D


In [35]:
print(threeD[2,1,0])

F


In [36]:
word = threeD[0,0,0] + threeD[0,1,0] + threeD[2,0,0] + threeD[1,1,0]

print(word)

ABED


<p style="font-size:28px; font-weight:bold;">Slicing</p>


In [48]:
slicing = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
#array[start:end:step]
print(slicing[1:3])#end is exclusive
print()
print(slicing[::2]) 
print()
print(slicing[::-1]) #reverse
#column selection
print()
print('3rd column')
print(slicing[:, 3]) #3rd column
print()
print('1st to 3rd column')
print(slicing[:, :3])
print()
print('1st two rows and its first two column')
print(slicing[:2, :2])

[[ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

3rd column
[ 4  8 12 16]

1st to 3rd column
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

1st two rows and its first two column
[[1 2]
 [5 6]]


<p style="font-size:28px; font-weight:bold;">Arithmetic</p>


In [52]:
arith = np.array([1,2,3])
# scalar
print(arith + 1)
print()
print(arith - 2)
print()
print(arith * 3)
print()
print(arith / 4)
print()
print(arith ** 5)

[2 3 4]

[-1  0  1]

[3 6 9]

[0.25 0.5  0.75]

[  1  32 243]


## 1. Arithmetic Functions

Basic element-wise math.

np.add(x, y) — Addition

np.subtract(x, y) — Subtraction

np.multiply(x, y) — Multiplication

np.divide(x, y) — Division

np.floor_divide(x, y) — Integer division

np.power(x, y) — x^y

np.float_power(x, y) — Power using float precision

np.remainder(x, y) / np.mod(x, y) — Remainder

np.fmod(x, y) — C-style remainder

np.negative(x) — Negation

np.positive(x) — Identity

np.absolute(x) / np.abs(x) — Absolute value

np.reciprocal(x) — 1/x

## 2. Trigonometric Functions

Operate in radians.

np.sin(x)

np.cos(x)

np.tan(x)

np.arcsin(x) — Inverse sine

np.arccos(x) — Inverse cosine

np.arctan(x) — Inverse tangent

np.arctan2(y, x) — Angle from vector components

## 3. Hyperbolic Functions

np.sinh(x)

np.cosh(x)

np.tanh(x)

np.arcsinh(x)

np.arccosh(x)

np.arctanh(x)

## 4. Exponential & Logarithmic Functions

np.exp(x) — e^x

np.expm1(x) — e^x − 1

np.exp2(x) — 2^x

np.log(x) — Natural log

np.log10(x) — Base-10 log

np.log2(x) — Base-2 log

np.log1p(x) — log(1+x)

## 5. Power & Root Functions

np.sqrt(x) — Square root

np.square(x) — x²

np.cbrt(x) — Cube root

## 6. Rounding Functions

np.ceil(x) — Round up

np.floor(x) — Round down

np.rint(x) — Round to nearest integer

np.trunc(x) — Remove decimal part

np.fix(x) — Round toward zero

np.round(x, n) — Round to n decimals

## 7. Comparison Functions

Return booleans.

np.equal(x, y)

np.not_equal(x, y)

np.greater(x, y)

np.greater_equal(x, y)

np.less(x, y)

np.less_equal(x, y)

np.maximum(x, y) — Element-wise max

np.minimum(x, y) — Element-wise min

## 8. Logical Functions

np.logical_and(x, y)

np.logical_or(x, y)

np.logical_xor(x, y)

np.logical_not(x)

## 9. Bitwise Functions

np.bitwise_and(x, y)

np.bitwise_or(x, y)

np.bitwise_xor(x, y)

np.invert(x) — Bitwise NOT

np.left_shift(x, y)

np.right_shift(x, y)

## 10. Floating-Point Checks

np.isnan(x) — Is NaN?

np.isinf(x) — Is +∞ or −∞?

np.isposinf(x) — Positive infinity

np.isneginf(x) — Negative infinity

np.isfinite(x) — Neither NaN nor inf

np.iscomplex(x) — Complex number

np.isreal(x) — Real number

np.signbit(x) — Sign bit

## 11. Miscellaneous Special Functions

np.sign(x) — Sign of number

np.clip(x, a, b) — Clamp to range

np.modf(x) — Fractional + integer parts

np.frexp(x) — Mantissa + exponent

np.ldexp(x, i) — x × 2^i

np.spacing(x) — Next float difference

np.nextafter(x, y) — Next float toward y

np.heaviside(x, h0) — Step function


<p style="font-size:28px; font-weight:bold;">Broadcasting</p>

<img src="broadcasting.png" width="50%">


In [65]:
array1 = np.array([[1, 2,3, 4]]) #1 row 4 columns
array2 = np.array([[1], [2], [3], [4]]) #4 rows 1 column

print(array1.shape) #rows of arr1` and arr2 is 1 and 4 but this will work since one of them is 1. same for colunmns
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


##Aggregate Functions - summarize data and typically return a single value
- `np.sum(a, axis=None)` – Sum of all elements or along an axis, Here axis=0 means sum all the elements of a column and axis = 1 means, sum all the elements in a row
- `np.prod(a, axis=None)` – Product of all elements or along an axis
- `np.min(a, axis=None)` – Minimum value
- `np.max(a, axis=None)` – Maximum value
- `np.argmin(a, axis=None)` – Index of minimum value
- `np.argmax(a, axis=None)` – Index of maximum value
- `np.mean(a, axis=None)` – Arithmetic mean
- `np.average(a, axis=None, weights=None)` – Weighted average
- `np.median(a, axis=None)` – Median value
- `np.var(a, axis=None)` – Variance
- `np.std(a, axis=None)` – Standard deviation
- `np.cumsum(a, axis=None)` – Cumulative sum
- `np.cumprod(a, axis=None)` – Cumulative product
- `np.any(a, axis=None)` – True if any element is True
- `np.all(a, axis=None)` – True if all elements are True
- `np.ptp(a, axis=None)` – Peak-to-peak (max - min)
- `np.nanmin(a, axis=None)` – Min ignoring NaN
- `np.nanmax(a, axis=None)` – Max ignoring NaN
- `np.nanmean(a, axis=None)` – Mean ignoring NaN
- `np.nanmedian(a, axis=None)` – Median ignoring NaN
- `np.nanvar(a, axis=None)` – Variance ignoring NaN
- `np.nanstd(a, axis=None)` – Std deviation ignoring NaN


<p style="font-size:28px; font-weight:bold;">Filtering</p>

In [70]:
ages = np.array([[21,17,19,20,16,30,18,65],
                [39, 22, 15, 99, 18, 18, 20, 21]])

teenagers = ages[ages<18]
print('Teenagers', teenagers)

adults = ages[(ages >= 18) & (ages < 50)] #we can not use and or since numpy is written in C, We have to use & , |
print('adults', adults)

evens = ages[ ages % 2 == 0]
print('Evens', evens)

Teenagers [17 16 15]
adults [21 19 20 30 18 39 22 18 18 20 21]
Evens [20 16 30 18 22 18 18 20]


In [72]:
#if we want to keep the array size same then we can use the where
#np.where(condition, array, replacement_value)
adults_new = np.where((ages >= 18) & (ages < 50), ages, 0)
print(adults_new)

[[21  0 19 20  0 30 18  0]
 [39 22  0  0 18 18 20 21]]
